export const ADD_INGREDIANT = "ADD_INGREDIANT";
export const REMOVE_INGREDIANT = "REMOVE_INGREDIANT";
export const SET_INGREDIANTS = "SET_INGREDIANTS";
export const FETCH_INGREDIANTS_FAILED = "FETCH_INGREDIANTS_FAILED";

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START ";
export const PURCHASE_INIT = "PURCHASE_INIT";
export const FETCH_ORDER_START = "FETCH_ORDER_START";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FALILED = "FETCH_ORDER_FALILED";
